"""Add cnpj to branches

Revision ID: 70d4f6g7h8j0
Revises: 60c3e5f6g7h8
Create Date: 2024-05-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d4f6g7h8j0'
down_revision = '60c3e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('cnpj', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'cnpj')
    # ### end Alembic commands ###
