"""Add category model and FK to item

Revision ID: add_category_model
Revises: initial_migration
Create Date: 2023-10-27 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_category_model'
down_revision: Union[str, None] = 'initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)

    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])

    # Populate categories from existing items (data migration)
    # This is tricky in alembic auto-gen, but simple in raw SQL if we trust uniqueness.
    # For now, we just create the table.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'category_id')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
