"""Add branch_id to users

Revision ID: add_user_branch
Revises: add_category_model
Create Date: 2023-10-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_user_branch'
down_revision: Union[str, None] = 'add_category_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    # ### end Alembic commands ###
